openapi: 3.2.0
info:
  title: Admin Openapi API
  description: This API exposes the admin operations of a Restate cluster, such as registering new service deployments, interacting with running invocations, register Kafka subscriptions, retrieve service metadata. For an overview, check out the Operate documentation. If you're looking for how to call your services, check out the Ingress HTTP API instead.
  version: 1.4.0
tags:
- name: Open API
paths:
  /openapi:
    get:
      tags:
      - Open API
      summary: OpenAPI Specification
      externalDocs:
        url: https://swagger.io/specification/
      operationId: openapi_spec
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
externalDocs:
  url: https://docs.restate.dev/operate/
